version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=d2gau69pqfq9t5
      - POSTGRES_USER=rsdxvtwclivwlo
      - POSTGRES_PASSWORD=3225fe19840dfba066e40975f68bb2a9d0b350d212686c86f38fdb39cf92368a
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db