# Generated by Django 3.1.7 on 2021-04-23 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210423_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likeCount',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
