# Generated by Django 3.1.7 on 2021-04-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likeCount',
        ),
    ]
